services:
  - type: web
    name: tweet-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chaiheadq.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chaiheadq.settings
      - key: PYTHON_VERSION
        value: 3.11